name: login_and_register
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  flutter_spinkit: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
     - images/
  fonts:
     - family: Lora
       fonts:
         - asset: fonts/Lora.ttf
         - asset: fonts/Lora-Italic.ttf
           style: italic
           weight: 400
  
