// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbboE4LSmlkq5N2ahHpmmKPhdgYOA9vM0',
    appId: '1:902079216217:web:a533e8876030f2ef704f48',
    messagingSenderId: '902079216217',
    projectId: 'login-d92c6',
    authDomain: 'login-d92c6.firebaseapp.com',
    storageBucket: 'login-d92c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGX6-_VrtsvIak_Q9TmTuf2T8aO63smIY',
    appId: '1:902079216217:android:24c3fa81a6a0d161704f48',
    messagingSenderId: '902079216217',
    projectId: 'login-d92c6',
    storageBucket: 'login-d92c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJp9azpYAEsK-MiNsDY0CPclOIE5XdFiU',
    appId: '1:902079216217:ios:5e97837cba6025c3704f48',
    messagingSenderId: '902079216217',
    projectId: 'login-d92c6',
    storageBucket: 'login-d92c6.appspot.com',
    iosClientId: '902079216217-tbqqb2v9qlvvuajsmf1t64710e3aej1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndRegister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJp9azpYAEsK-MiNsDY0CPclOIE5XdFiU',
    appId: '1:902079216217:ios:5e97837cba6025c3704f48',
    messagingSenderId: '902079216217',
    projectId: 'login-d92c6',
    storageBucket: 'login-d92c6.appspot.com',
    iosClientId: '902079216217-tbqqb2v9qlvvuajsmf1t64710e3aej1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginAndRegister',
  );
}
